name: vmat-diffusion
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - alsa-lib=1.2.15.1
  - anyio=4.12.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attr=2.5.2
  - attrs=25.4.0
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - blas=1.0
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.15.2
  - ca-certificates=2025.12.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpp-expected=1.3.1
  - cpython=3.12.12
  - cryptography=46.0.3
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.9.79
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=4.2.2
  - filelock=3.20.1
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetds=1.5.10
  - freetype=2.14.1
  - geos=3.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=9.0.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - ittapi=3.26.4
  - ittapi-static=3.26.4
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.2
  - jaraco.functools=4.4.0
  - jedi=0.19.2
  - jeepney=0.9.0
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.7.0
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - jxrlib=1.1
  - keyring=25.7.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libarchive=3.8.2
  - libavif16=1.3.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.77
  - libclang-cpp18.1=18.1.8
  - libclang13=21.1.0
  - libcublas=12.4.5.8
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.80.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libllvm18=18.1.8
  - libllvm21=21.1.0
  - libmamba=2.4.0
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnsl=2.0.0
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=16.11
  - libsodium=1.0.20
  - libsolv=0.7.35
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libudev1=258.3
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mamba=2.4.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - monai=1.5.1
  - more-itertools=10.8.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.6.1
  - nlohmann_json-abi=3.12.0
  - notebook=7.5.1
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - numpy-base=2.3.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openh264=2.1.1
  - openjpeg=2.5.3
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.43
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydicom=3.0.1
  - pygments=2.19.2
  - pymedphys_coordsandscales=0.11.0
  - pymedphys_databases=0.11.0
  - pymedphys_electronfactors=0.11.0
  - pymedphys_fileformats=0.11.0
  - pymedphys_labs=0.11.0
  - pymedphys_logfiles=0.11.0
  - pymedphys_mudensity=0.11.0
  - pymedphys_pinnacle=0.11.0
  - pymedphys_xlwings=0.11.0
  - pymssql=2.3.11
  - pyparsing=3.3.1
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.12
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - rav1e=0.7.1
  - rdma-core=60.0
  - readline=8.3
  - referencing=0.37.0
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scikit-image=0.26.0
  - scipy=1.16.3
  - secretstorage=3.4.1
  - send2trash=2.0.0
  - setuptools=80.9.0
  - shapely=2.1.2
  - simdjson=4.2.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - terminado=0.18.1
  - tifffile=2024.12.12
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.3.0
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - unixodbc=2.3.14
  - uri-template=1.3.0
  - urllib3=2.6.2
  - wayland=1.23.1
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - x264=1!157.20191217
  - xarray=2025.12.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - dataclasses==0.6
      - datasets==4.4.2
      - diffusers==0.36.0
      - dill==0.4.0
      - einops==0.8.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nibabel==5.3.3
      - numba==0.63.1
      - opencv-python==4.13.0.90
      - propcache==0.4.1
      - protobuf==6.33.4
      - pyarrow==22.0.0
      - pymedphys==0.41.0
      - pytorch-lightning==2.6.0
      - regex==2025.11.3
      - rich==14.2.0
      - rt-utils==1.2.7
      - safetensors==0.7.0
      - simpleitk==2.5.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.22.1
      - tomlkit==0.14.0
      - torchmetrics==1.8.2
      - transformers==4.57.3
      - werkzeug==3.1.5
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/wrockey/miniconda3/envs/vmat-diffusion
