name: vmat-win
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - attrs==25.4.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - grpcio==1.76.0
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.6.1
      - nibabel==5.3.3
      - numpy==2.3.5
      - packaging==25.0
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - pydicom==3.0.1
      - pygments==2.19.2
      - pymedphys==0.41.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.0
      - pyyaml==6.0.3
      - rich==14.2.0
      - scikit-image==0.26.0
      - scipy==1.17.0
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tifffile==2026.1.14
      - tomlkit==0.14.0
      - torch==2.6.0+cu124
      - torchmetrics==1.8.2
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - werkzeug==3.1.5
      - yarl==1.22.0
prefix: C:\pinokio\bin\miniconda\envs\vmat-win
